[package]
name = "hello_crates_and_modules"
version = "0.1.0"
authors = ["WiZ3910 <mikuto.matsuo@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
